name: 'PlayEveryWare/action-find-app-installation'
description: 'Finds the installation id for a GitHub application'

inputs:
  application-id:
    description: Application id of the GitHub app
    default: 239145
    required: true
  private-key:
    description: Private key for the application
    required: true
  repository:
    description: Repository to check
  repository-owner:
    description: Repository owner to check

outputs:
  installation-id:
    description: Id of the application installation

runs:
  using: node20
  main: dist/index.js
